# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - main
resources:
  repositories:
  - repository: self
variables:
- name: dockerRegistryServiceConnection
  value: '04ce9547-dbff-4160-958f-d3ae18e0e5b6'
- name: imageRepository
  value: 'drawsmcgrawpipelinesjavascriptdocker'
- name: containerRegistry
  value: 'drmaloneregistry.azurecr.io'
- name: dockerfilePath
  value: '**/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
- name: imagePullSecret
  value: 'drmaloneregistry9428-auth'
- name: vmImageName
  value: 'ubuntu-latest'
- name: k8sNamespaceForPR
  value: 'review-app-$(System.PullRequest.PullRequestId)'
- name: k8sServiceConnection
  value: drmalone-k8s
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: wiz@0
      displayName: Wiz CLI Scan
      inputs:
        command: 'iac'
        clientid: $(WIZ_CLIENT_ID)
        secret: $(WIZ_CLIENT_SECRET)
        succeedOnFailures: true
        policyHitsOnly: false
        scanTags: "cicd=ado,app=terraform"
        path: '.'
        name: 'Terraform Code'
        scanSecrets: true
        wizenv: 'fedramp'


    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: ecdc45f6-832d-4ad9-b52b-ee49e94659be@0
      inputs:
        targetPath: manifests
        artifactName: manifests

    - task: KubernetesManifest@0
      displayName: Create imagePullSecret
      inputs:
        action: createSecret
        secretName: $(imagePullSecret)
        dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: $(k8sServiceConnection)



# - stage: Sanity
#   dependsOn: Build
#   displayName: 'Sanity Test'
#   jobs:
#   - job: testing
#     displayName: 'Testing Job'
#     steps:
#     - task: Bash@3
#       inputs:
#         targetType: 'inline'
#         script: 'echo ''I am losing my mind'''















# - task: KubernetesManifest@1
#   inputs:
#     action: 'deploy'
#     connectionType: 'kubernetesServiceConnection'
#     kubernetesServiceConnection: 'drmalone-k8s'
#     namespace: 'default'
#     manifests: '$(Pipeline.Workspace)/manifests/deployment.yml                 $(Pipeline.Workspace)/manifests/service.yml'
#     imagePullSecrets: '$(imagePullSecrets)'




- stage: Deploy
  displayName: Deploy stage
  dependsOn:
  - Build
  jobs:
  - deployment: Deployment
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment:
      name: 'drawsmcgrawpipelinesjavascriptdocker.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
              connectionType: 'kubernetesServiceConnection'
              kubernetesServiceConnection: $(k8sServiceConnection)
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              connectionType: 'kubernetesServiceConnection'
              kubernetesServiceConnection: $(k8sServiceConnection)
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)


  - deployment: DeployPullRequest
    displayName: Deploy Pull request
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/pull/'))
    pool:
      vmImage: $(vmImageName)
    environment:
      name: 'drawsmcgrawpipelinesjavascriptdocker.$(k8sNamespaceForPR)'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ReviewApp@0
            inputs:
              resourceName: default
          - task: Kubernetes@1
            displayName: 'Create a new namespace for the pull request'
            inputs:
              command: apply
              useConfigurationFile: true
              inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "$(k8sNamespaceForPR)" }}'
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              namespace: $(k8sNamespaceForPR)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
          - task: KubernetesManifest@0
            displayName: Deploy to the new namespace in the Kubernetes cluster
            inputs:
              action: deploy
              namespace: $(k8sNamespaceForPR)
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
          - task: Kubernetes@1
            name: get
            displayName: 'Get services in the new namespace'
            continueOnError: true
            inputs:
              command: get
              namespace: $(k8sNamespaceForPR)
              arguments: svc
              outputFormat: jsonpath='http://{.items[0].status.loadBalancer.ingress[0].ip}:{.items[0].spec.ports[0].port}'
          - task: CmdLine@2
            inputs:
              script: |
                url="$(get.KubectlOutput)"
                message="Your review app has been deployed"
                if [ ! -z "$url" -a "$url" != "http://:" ]
                then
                  message="${message} and is available at $url.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app."
                fi
                echo "##vso[task.setvariable variable=GITHUB_COMMENT]$message"